version: '3.9'
services:
  redis:
    image: redis
    ports:
      - 6379:6379

  web-server:
    image: web-server
    ports:
      - 4200:4200

  server:
    image: server
    ports:
      - 3000:3000

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pass123